/* eslint-disable @next/next/no-img-element */
import Footer from "@/components/structure/footer";
import Navigation from "@/components/structure/navigation";
import type { Metadata } from "next";
import './globals.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
        <meta
          name="description"
          content={`Personal Site for Nathaniel J. Clement`}
        />
        <meta property="og:image" content={"/logo.png"} />
      </head>
      <body
        suppressHydrationWarning={true}
        className={`antialiased`}
      >

        <div className='flex flex-col items-center justify-top min-h-screen gap-y-8 text-gray-700 mt-6'>
          <img alt='Logo Image' src='/logo.png' className='p-4 w-full max-w-xl' />
          <div className='w-full max-w-3xl'>
            <Navigation></Navigation>
          </div>
          <div className='px-2 sm:p-6'>
            <main>{children}</main>
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
